<?php

/**
 * A curated, ready-to-suggest set of destination templates spanning every
 * continent -- category (City / Coastal & Beach / Cultural & Historic /
 * Nature & Parks / Nature & Coastal), best season, a sensible trip length,
 * and a one-line overview. Used to prefill the "Get inspired" browse page
 * and to suggest sensible defaults in the trip wizard when a destination
 * matches one of these.
 *
 * Source: docs/itinerary-templates.xlsx (the Travel2gether template index).
 */

return [
    [
        'category' => 'City',
        'continent' => 'Asia',
        'destination' => 'Bangkok',
        'country' => 'Thailand',
        'region' => 'Central Thailand',
        'best_season' => 'Nov-Feb (cool, dry); avoid Apr (hottest)',
        'trip_length' => '3 days',
        'overview' => 'Grand palaces, canal-side temples, legendary street food, and rooftop bars — intensely hot and humid most of the year, so pace the outdoor time.',
        'photo_folder' => '/photos/bangkok/',
    ],
    [
        'category' => 'City',
        'continent' => 'Asia',
        'destination' => 'Dubai',
        'country' => 'United Arab Emirates',
        'region' => 'Middle East',
        'best_season' => 'Nov-Mar (mild); avoid Jun-Aug extreme heat',
        'trip_length' => '3 days',
        'overview' => 'A ultramodern desert city of record-breaking towers, luxury malls, and traditional souks along a historic creek.',
        'photo_folder' => '/photos/dubai/',
    ],
    [
        'category' => 'City',
        'continent' => 'Asia',
        'destination' => 'Fukuoka',
        'country' => 'Japan',
        'region' => 'Kyushu',
        'best_season' => 'Mar-May, Sep-Nov',
        'trip_length' => '2 days',
        'overview' => 'Japan\'s food-lovers\' city — famous yatai street-food stalls, a rebuilt castle park, and an easy day-trip shrine town.',
        'photo_folder' => '/photos/fukuoka/',
    ],
    [
        'category' => 'City',
        'continent' => 'Asia',
        'destination' => 'Osaka',
        'country' => 'Japan',
        'region' => 'Kansai',
        'best_season' => 'Mar-May, Sep-Nov',
        'trip_length' => '3 days',
        'overview' => 'Japan\'s food capital — neon-lit Dotonbori, a landmark castle, and a major theme park, with easy access to Kyoto and Nara.',
        'photo_folder' => '/photos/osaka/',
    ],
    [
        'category' => 'City',
        'continent' => 'Asia',
        'destination' => 'Singapore',
        'country' => 'Singapore',
        'region' => 'Southeast Asia',
        'best_season' => 'Year-round (tropical); Feb-Apr is driest',
        'trip_length' => '3 days',
        'overview' => 'A dense, ultra-clean city-state of futuristic gardens, hawker food, and multicultural districts, with an excellent metro.',
        'photo_folder' => '/photos/singapore/',
    ],
    [
        'category' => 'City',
        'continent' => 'Asia',
        'destination' => 'Yokohama',
        'country' => 'Japan',
        'region' => 'Kanagawa, adjacent to Tokyo',
        'best_season' => 'Year-round',
        'trip_length' => '1 day',
        'overview' => 'Japan\'s largest Chinatown, a lit-up harbour skyline, and a relocated-buildings garden — a low-stress, mostly-covered day ~30 min from Shinjuku.',
        'photo_folder' => '/photos/yokohama/',
    ],
    [
        'category' => 'Coastal & Beach',
        'continent' => 'Asia',
        'destination' => 'Bali',
        'country' => 'Indonesia',
        'region' => 'Southeast Asia',
        'best_season' => 'Apr-Oct (dry season)',
        'trip_length' => '4 days',
        'overview' => 'Rice terraces, temples, surf beaches, and a strong wellness/yoga scene, spread across distinct regions (Ubud, Seminyak, Uluwatu) best linked by private driver.',
        'photo_folder' => '/photos/bali/',
    ],
    [
        'category' => 'Cultural & Historic',
        'continent' => 'Asia',
        'destination' => 'Kamakura & Enoshima',
        'country' => 'Japan',
        'region' => 'Kanagawa, near Tokyo/Yokohama',
        'best_season' => 'Year-round; spring & autumn foliage best',
        'trip_length' => '1 day',
        'overview' => 'Great Buddha, hillside temples, the anime-famous Enoden coastal railway, and Enoshima island — an easy day trip ~1h from Tokyo or Yokohama.',
        'photo_folder' => '/photos/kamakura/',
    ],
    [
        'category' => 'Cultural & Historic',
        'continent' => 'Asia',
        'destination' => 'Kyoto',
        'country' => 'Japan',
        'region' => 'Kansai',
        'best_season' => 'Mar-May (cherry blossom), Oct-Nov (autumn foliage)',
        'trip_length' => '3 days',
        'overview' => 'A thousand years as Japan\'s capital — temples, geisha districts, bamboo groves, and traditional gardens across a walkable, bike-friendly city.',
        'photo_folder' => '/photos/kyoto/',
    ],
    [
        'category' => 'Cultural & Historic',
        'continent' => 'Asia',
        'destination' => 'Nikko',
        'country' => 'Japan',
        'region' => 'Tochigi, near Tokyo',
        'best_season' => 'Apr-Nov; spectacular autumn foliage (Oct-Nov)',
        'trip_length' => '1 day (2 if adding Oku-Nikko)',
        'overview' => 'UNESCO shrine complex, a mountain switchback road, and one of Japan\'s three great waterfalls — ~2h from Tokyo via Tobu Railway.',
        'photo_folder' => '/photos/nikko/',
    ],
    [
        'category' => 'Nature & Coastal',
        'continent' => 'Asia',
        'destination' => 'Izu Peninsula',
        'country' => 'Japan',
        'region' => 'Shizuoka, near Tokyo',
        'best_season' => 'Apr–Nov (best); onsen season all year',
        'trip_length' => '2 days (overnight)',
        'overview' => 'Onsen towns, coastal cliffs and a seven-waterfall hiking trail, ~2h from Tokyo by Shinkansen. A slower, less-touristed alternative to Hakone.',
        'photo_folder' => '/photos/izu/',
    ],
    [
        'category' => 'Nature & Parks',
        'continent' => 'Asia',
        'destination' => 'Hakone',
        'country' => 'Japan',
        'region' => 'Kanagawa, near Tokyo',
        'best_season' => 'Year-round; clearest Mt. Fuji views Dec-Feb',
        'trip_length' => '2 days (1 night onsen stay)',
        'overview' => 'The classic loop — switchback railway, volcanic valley ropeway, a pirate-ship lake cruise, an open-air sculpture museum, and onsen — all on one transport pass.',
        'photo_folder' => '/photos/hakone/',
    ],
    [
        'category' => 'City',
        'continent' => 'Europe',
        'destination' => 'Barcelona',
        'country' => 'Spain',
        'region' => 'Catalonia',
        'best_season' => 'Apr-Jun, Sep-Oct (mild, fewer crowds)',
        'trip_length' => '3 days',
        'overview' => 'Gaudi architecture, Gothic Quarter lanes, beach time, and world-class tapas — a compact, walkable city with an excellent metro.',
        'photo_folder' => '/photos/barcelona/',
    ],
    [
        'category' => 'City',
        'continent' => 'Europe',
        'destination' => 'Paris',
        'country' => 'France',
        'region' => 'Ile-de-France',
        'best_season' => 'Apr-Jun, Sep-Oct (mild, fewer crowds)',
        'trip_length' => '3 days',
        'overview' => 'Iconic landmarks, world-class museums, and neighborhood cafe culture — best explored on foot and by metro.',
        'photo_folder' => '/photos/paris/',
    ],
    [
        'category' => 'Coastal & Beach',
        'continent' => 'Europe',
        'destination' => 'French Riviera & Provence',
        'country' => 'France',
        'region' => 'Provence-Alpes-Cote d\'Azur',
        'best_season' => 'May-Jun, Sep (mild, less crowded than Jul-Aug)',
        'trip_length' => '3 days',
        'overview' => 'Mediterranean coastal glamour (Nice, Cannes, Monaco) paired with lavender-and-hilltop-village Provence inland.',
        'photo_folder' => '/photos/french-riviera/',
    ],
    [
        'category' => 'Coastal & Beach',
        'continent' => 'Europe',
        'destination' => 'Santorini',
        'country' => 'Greece',
        'region' => 'Cyclades',
        'best_season' => 'May-Jun, Sep-Oct (mild, fewer crowds than Jul-Aug)',
        'trip_length' => '3 days',
        'overview' => 'Whitewashed cliffside villages, dramatic caldera views, and volcanic beaches on a small, walkable Cycladic island.',
        'photo_folder' => '/photos/santorini/',
    ],
    [
        'category' => 'Cultural & Historic',
        'continent' => 'Europe',
        'destination' => 'Florence',
        'country' => 'Italy',
        'region' => 'Tuscany',
        'best_season' => 'Apr-Jun, Sep-Oct',
        'trip_length' => '3 days',
        'overview' => 'The cradle of the Renaissance — world-class art museums, a landmark cathedral dome, and Tuscan countryside just outside the city.',
        'photo_folder' => '/photos/florence/',
    ],
    [
        'category' => 'Cultural & Historic',
        'continent' => 'Europe',
        'destination' => 'Rome',
        'country' => 'Italy',
        'region' => 'Lazio',
        'best_season' => 'Apr-Jun, Sep-Oct',
        'trip_length' => '3 days',
        'overview' => 'Ancient ruins, Vatican treasures, and a lively piazza-and-fountain streetlife — a dense, walkable historic core.',
        'photo_folder' => '/photos/rome/',
    ],
    [
        'category' => 'Nature & Parks',
        'continent' => 'Europe',
        'destination' => 'Reykjavik & the Golden Circle',
        'country' => 'Iceland',
        'region' => 'Southwest Iceland',
        'best_season' => 'Jun-Aug (midnight sun); Sep-Mar (northern lights, needs dark skies)',
        'trip_length' => '3 days',
        'overview' => 'A small, walkable capital as the base for waterfalls, geysers, and geothermal spas — the Golden Circle loop is the essential first day trip.',
        'photo_folder' => '/photos/reykjavik-iceland/',
    ],
    [
        'category' => 'City',
        'continent' => 'North America',
        'destination' => 'Boston',
        'country' => 'USA',
        'region' => 'Massachusetts',
        'best_season' => 'May-Jun, Sep-Oct (mild)',
        'trip_length' => '2 days',
        'overview' => 'Revolutionary War history along the Freedom Trail, historic Harvard/MIT across the river, and a strong Italian food scene in the North End.',
        'photo_folder' => '/photos/boston/',
    ],
    [
        'category' => 'City',
        'continent' => 'North America',
        'destination' => 'New York City',
        'country' => 'USA',
        'region' => 'New York',
        'best_season' => 'Apr-Jun, Sep-Nov (mild); Dec for holiday atmosphere',
        'trip_length' => '3 days',
        'overview' => 'Iconic skyline, world-class museums, and a different neighborhood personality on every block — best covered by subway and on foot.',
        'photo_folder' => '/photos/new-york-city/',
    ],
    [
        'category' => 'City',
        'continent' => 'North America',
        'destination' => 'Salt Lake City, Utah',
        'country' => 'USA',
        'region' => 'Utah',
        'best_season' => 'May-Sep (city/outdoors); Nov-Mar (skiing nearby)',
        'trip_length' => '2 days',
        'overview' => 'A walkable capital city anchored by Temple Square, with world-class ski resorts and canyon hiking a short drive away.',
        'photo_folder' => '/photos/salt-lake-city/',
    ],
    [
        'category' => 'City',
        'continent' => 'North America',
        'destination' => 'Washington, D.C.',
        'country' => 'USA',
        'region' => 'Mid-Atlantic',
        'best_season' => 'Mar-Apr (cherry blossoms), Sep-Nov (mild)',
        'trip_length' => '3 days',
        'overview' => 'The National Mall\'s monuments and free Smithsonian museums, plus historic Georgetown.',
        'photo_folder' => '/photos/washington-dc/',
    ],
    [
        'category' => 'Nature & Parks',
        'continent' => 'North America',
        'destination' => 'Antelope Canyon & Page, Arizona',
        'country' => 'USA',
        'region' => 'Arizona',
        'best_season' => 'Mar-Oct (best light for Antelope Canyon around midday, Apr-Sep)',
        'trip_length' => '2 days',
        'overview' => 'Sculpted slot canyons and the iconic Horseshoe Bend, all accessible only through guided tours run by the Navajo Nation.',
        'photo_folder' => '/photos/antelope-canyon-page/',
    ],
    [
        'category' => 'Nature & Parks',
        'continent' => 'North America',
        'destination' => 'Grand Canyon National Park',
        'country' => 'USA',
        'region' => 'Arizona',
        'best_season' => 'Mar-May, Sep-Nov (South Rim year-round; North Rim closed Oct-May)',
        'trip_length' => '2 days',
        'overview' => 'One of the world\'s great natural wonders — mile-deep canyon views, rim-trail walks, and sunrise/sunset viewpoints.',
        'photo_folder' => '/photos/grand-canyon/',
    ],
    [
        'category' => 'Nature & Parks',
        'continent' => 'North America',
        'destination' => 'Tahoe & Reno',
        'country' => 'USA',
        'region' => 'California / Nevada border',
        'best_season' => 'Jun-Sep (lake/beach); Dec-Mar (ski season)',
        'trip_length' => '3 days',
        'overview' => 'An alpine lake, casino nightlife, and a scenic mountain loop — Reno as the gateway, Tahoe for the outdoors.',
        'photo_folder' => '/photos/tahoe-reno/',
    ],
    [
        'category' => 'Nature & Parks',
        'continent' => 'North America',
        'destination' => 'Yosemite National Park',
        'country' => 'USA',
        'region' => 'California, Sierra Nevada',
        'best_season' => 'May-Oct (Tioga Road/high country open); year-round for the Valley',
        'trip_length' => '3 days',
        'overview' => 'Granite cliffs, giant sequoias, and waterfalls in one of the US\'s most iconic national parks.',
        'photo_folder' => '/photos/yosemite/',
    ],
    [
        'category' => 'Cultural & Historic',
        'continent' => 'South America',
        'destination' => 'Cusco & Machu Picchu',
        'country' => 'Peru',
        'region' => 'Cusco Region, Andes',
        'best_season' => 'May-Sep (dry season)',
        'trip_length' => '4 days',
        'overview' => 'The former Inca capital and the iconic mountaintop citadel, connected by a scenic train through the Sacred Valley — high altitude requires acclimatization.',
        'photo_folder' => '/photos/cusco-machu-picchu/',
    ],
    [
        'category' => 'City',
        'continent' => 'Africa',
        'destination' => 'Cape Town',
        'country' => 'South Africa',
        'region' => 'Western Cape',
        'best_season' => 'Nov-Mar (summer, warm/dry); Apr-May and Sep-Oct are shoulder seasons',
        'trip_length' => '3 days',
        'overview' => 'A city framed by Table Mountain and two oceans, with vineyards, penguin colonies, and dramatic coastal drives all close by.',
        'photo_folder' => '/photos/cape-town/',
    ],
    [
        'category' => 'Cultural & Historic',
        'continent' => 'Africa',
        'destination' => 'Marrakech',
        'country' => 'Morocco',
        'region' => 'Marrakech-Safi',
        'best_season' => 'Mar-May, Sep-Nov (avoid extreme summer heat)',
        'trip_length' => '3 days',
        'overview' => 'A maze of a medina, palatial riads, vibrant souks, and the legendary Jemaa el-Fnaa square that transforms from day to night.',
        'photo_folder' => '/photos/marrakech/',
    ],
    [
        'category' => 'City',
        'continent' => 'Oceania',
        'destination' => 'Sydney',
        'country' => 'Australia',
        'region' => 'New South Wales',
        'best_season' => 'Sep-Nov, Mar-May (mild); Dec-Feb is peak summer/beach season',
        'trip_length' => '3 days',
        'overview' => 'Harbour icons, coastal walks, and beach culture — a compact, walkable, ferry-friendly city.',
        'photo_folder' => '/photos/sydney/',
    ],
    [
        'category' => 'Nature & Parks',
        'continent' => 'Oceania',
        'destination' => 'Queenstown',
        'country' => 'New Zealand',
        'region' => 'South Island, Otago',
        'best_season' => 'Dec-Feb (summer, hiking/lake); Jun-Sep (ski season)',
        'trip_length' => '3 days',
        'overview' => 'New Zealand\'s adventure capital — bungy jumping, alpine lakes, and access to some of the country\'s most dramatic scenery.',
        'photo_folder' => '/photos/queenstown/',
    ],
    [
        'category' => 'City',
        'continent' => 'Asia',
        'destination' => 'Istanbul & Cappadocia',
        'country' => 'Turkey',
        'region' => 'Marmara & Central Anatolia',
        'best_season' => 'Apr-May, Sep-Oct',
        'trip_length' => '4 days',
        'overview' => 'A city spanning two continents, plus a side trip to Cappadocia\'s fairy-chimney landscape and hot-air balloons — Turkey is the 4th most-visited country in the world.',
        'photo_folder' => '/photos/istanbul-cappadocia/',
    ],
    [
        'category' => 'City',
        'continent' => 'Europe',
        'destination' => 'London',
        'country' => 'United Kingdom',
        'region' => 'England',
        'best_season' => 'May-Sep (mild, longer daylight)',
        'trip_length' => '3 days',
        'overview' => 'A dense, historic capital of royal palaces, world-class free museums, and a spread of distinct neighborhoods, all connected by the Underground.',
        'photo_folder' => '/photos/london/',
    ],
    [
        'category' => 'City',
        'continent' => 'Europe',
        'destination' => 'Berlin',
        'country' => 'Germany',
        'region' => 'Berlin',
        'best_season' => 'May-Sep (mild)',
        'trip_length' => '3 days',
        'overview' => 'A city defined by its 20th-century history — Cold War remnants, world-class museums, and a famously vibrant, alternative culture scene.',
        'photo_folder' => '/photos/berlin/',
    ],
    [
        'category' => 'City',
        'continent' => 'Europe',
        'destination' => 'Madrid',
        'country' => 'Spain',
        'region' => 'Community of Madrid',
        'best_season' => 'Apr-Jun, Sep-Oct',
        'trip_length' => '3 days',
        'overview' => 'Spain\'s capital — world-class art museums, grand royal architecture, and a legendary late-night tapas and nightlife culture.',
        'photo_folder' => '/photos/madrid/',
    ],
    [
        'category' => 'City',
        'continent' => 'Europe',
        'destination' => 'Athens',
        'country' => 'Greece',
        'region' => 'Attica',
        'best_season' => 'Apr-Jun, Sep-Oct',
        'trip_length' => '3 days',
        'overview' => 'The birthplace of democracy — ancient ruins overlooking a modern Mediterranean capital, and the gateway to the Greek islands.',
        'photo_folder' => '/photos/athens/',
    ],
    [
        'category' => 'City',
        'continent' => 'North America',
        'destination' => 'Mexico City',
        'country' => 'Mexico',
        'region' => 'CDMX',
        'best_season' => 'Mar-May, Oct-Nov (dry, mild)',
        'trip_length' => '3 days',
        'overview' => 'A high-altitude megacity of world-class museums, ancient pyramids nearby, and one of the world\'s great food scenes.',
        'photo_folder' => '/photos/mexico-city/',
    ],
    [
        'category' => 'City',
        'continent' => 'Asia',
        'destination' => 'Beijing',
        'country' => 'China',
        'region' => 'Beijing Municipality',
        'best_season' => 'Apr-May, Sep-Oct',
        'trip_length' => '3 days',
        'overview' => 'Imperial China\'s ancient capital — the Forbidden City, the Great Wall, and a rapidly modern city built around thousands of years of history.',
        'photo_folder' => '/photos/beijing/',
    ],
    [
        'category' => 'City',
        'continent' => 'Europe',
        'destination' => 'Venice',
        'country' => 'Italy',
        'region' => 'Veneto',
        'best_season' => 'Apr-Jun, Sep-Oct (avoid Aug heat and Nov-Feb acqua alta flooding risk)',
        'trip_length' => '2 days',
        'overview' => 'A city built on water — canals, gondolas, and centuries of maritime-trade wealth packed into a compact, car-free historic core.',
        'photo_folder' => '/photos/venice/',
    ],
];
